FROM alpine

RUN apk update && apk upgrade && apk add vim

CMD	vim


# apk is the tool used to install, upgrade, or delete software on a running sytem
# update	Update the index of available packages
# upgrade	Upgrade the currently installed packages
# add	Add new packages to the running system

# How to build it
# docker build -t ex00 .

# How to run it
# docker run --rm -ti ex00
