FROM ubuntu

RUN apt-get update && apt-get upgrade -y && apt-get install -y default-jdk default-jre git vim emacs


# How to build it?
# docker build -t ex02 .

# How to run it?
# docker run --rm -ti ex02
